name: Install Bun and package dependencies
description: "Install dependencies with Bun"

runs:
  using: "composite"
  steps:
    - name: Install Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: Install dependencies
      shell: bash
      run: bun install --frozen-lockfile

    - name: Install Vercel CLI
      shell: bash
      run: bun add -g vercel
